/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/projects/[projectId]': RouteRecordInfo<'/admin/projects/[projectId]', '/admin/projects/:projectId', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/callback/': RouteRecordInfo<'/callback/', '/callback', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/documentation/': RouteRecordInfo<'/documentation/', '/documentation', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/projects/[projectId]/': RouteRecordInfo<'/projects/[projectId]/', '/projects/:projectId', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/[appId]': RouteRecordInfo<'/projects/[projectId]/[appId]', '/projects/:projectId/:appId', { projectId: ParamValue<true>, appId: ParamValue<true> }, { projectId: ParamValue<false>, appId: ParamValue<false> }, '/projects/[projectId]/[appId]/logs'>,
    '/projects/[projectId]/[appId]/logs': RouteRecordInfo<'/projects/[projectId]/[appId]/logs', '/projects/:projectId/:appId/logs', { projectId: ParamValue<true>, appId: ParamValue<true> }, { projectId: ParamValue<false>, appId: ParamValue<false> }>,
    '/projects/[projectId]/apps/[appId]/logs': RouteRecordInfo<'/projects/[projectId]/apps/[appId]/logs', '/projects/:projectId/apps/:appId/logs', { projectId: ParamValue<true>, appId: ParamValue<true> }, { projectId: ParamValue<false>, appId: ParamValue<false> }>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/admin/projects/[projectId].vue': {
      routes: '/admin/projects/[projectId]'
      views: never
    }
    'src/pages/callback/index.vue': {
      routes: '/callback/'
      views: never
    }
    'src/pages/dashboard/index.vue': {
      routes: '/dashboard/'
      views: never
    }
    'src/pages/documentation/index.vue': {
      routes: '/documentation/'
      views: never
    }
    'src/pages/projects/index.vue': {
      routes: '/projects/'
      views: never
    }
    'src/pages/projects/[projectId]/index.vue': {
      routes: '/projects/[projectId]/'
      views: never
    }
    'src/pages/projects/[projectId]/[appId].vue': {
      routes: '/projects/[projectId]/[appId]' | '/projects/[projectId]/[appId]/logs'
      views: 'default'
    }
    'src/pages/projects/[projectId]/[appId]/logs.vue': {
      routes: '/projects/[projectId]/[appId]/logs'
      views: never
    }
    'src/pages/projects/[projectId]/apps/[appId]/logs.vue': {
      routes: '/projects/[projectId]/apps/[appId]/logs'
      views: never
    }
    'src/pages/settings/index.vue': {
      routes: '/settings/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
